import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  currentUser: null,
};

export const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    loginSuccess: (state, action) => {
      state.currentUser = action.payload.user;
      localStorage.setItem("fittrack-app-token", action.payload.token);
    },
    logout: (state) => {
      state.currentUser = null;
      localStorage.removeItem("fittrack-app-token"); // corrected typo here
    },
  },
});

// Export actions generated by createSlice
export const { loginSuccess, logout } = userSlice.actions;

// Export the reducer function generated by createSlice
export default userSlice.reducer;
